#🔹 Kubernetes — Create a ReplicaSet with 3 Replicas

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pathnex-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pathnex-app
  template:
    metadata:
      labels: 
        app: pathnex-app
    spec: 
      containers:
        - name: app 
          image: nginx
          ports:
            - containerPort: 80
            