// Jenkins Pipeline — Simulated Deployment

pipeline {
    agent any 
    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'staging', 'prod'], description: 'Deployment Environment' )
    }
    environment {
        FIRM_NAME = "Nephronix"
    }

    stages {
        stage('Deploy'){
            steps {
                sh 'echo "Deploying $FIRM_NAME application to $ENVIRONMENT"'
            }
        }
    }
}
