# Python Application
print("Hello Pathnex")

# Docker File

FROM python:3.11
WORKDIR /opt/pathnex/python-app 
COPY app.py /opt/pathnex/python-app
CMD [ "python", "/opt/pathnex/python-app/app.py" ]

# Real Path
/opt/pathnex/python-app