## 🔹 GitLab CI — NodeJS Build

stages:
  - install
  - test
  - build 

node-install:
  stage: install 
  image: node:16
  script:
    - git clone https://github.com/Pathnex/sample-node-app.git
    - cd sample-node-app 
    - npm install 

node-test:
  stage: test 
  image: node:16 
  script:
    - cd sample-node-app 
    - npm test

node-build:
  stage: build 
  image: node:16 
  script:
    - cd sample-node-app 
    - npm run build