stages:
  - build
  - deploy


build:
  stage: build 
  image: maven:3.8.1-jdk-17
  script:
    - git clone https://github.com/Pathnex/sample-java-app.git
    - cd sample-java-app 
    - mvn clean compile 
  only:
    - main

deploy:
  stage: deploy 
  image: alpine:latest 
  script:
     - echo "Deploying to $CI_ENVIRONMENT_NAME by Pathnex"
  only:
    variables:
      - $CI_ENVIRONMENT_NAME == "dev"