## 🔹 GitLab CI — Maven Build

stages:
  - build 
  - test 
  - package 

maven-build:
  stage: build 
  image: maven:3.8.1-jdk-17
  script:
    - git clone https://github.com/Pathnex/sample-java-app.git
    - cd sample-java-app 
    - mvn clean compile 
  
maven-test:
  stage: test 
  image: maven:3.8.1-jdk-17 
  script:
    - cd sample-java-app 
    - mvn test 

maven-package:
  stage: package 
  image: maven:3.8.1-jdk-17 
  script:
    - cd sample-java-app 
    - mvn package 