apiVersion: v1
kind: Pod
metadata: 
  name: pathnex-probe-pod
spec:
  containers:
    - name: web
      images: nginx 
      livenessProbe:
        httpGet:
          path: /
          port: 80
          initialDelaySeconds: 5
      redainessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3