// Jenkins Pipeline — Run Unit & Integration Tests

pipeline {
    agent any 
    environment {
        FIRM_NAME = "Nephronix"
        TEAM      = "QA"
        ENV       = "dev"
    }
    stages{
        stage('Checkout'){
            steps {
                 git url: 'https://github.com/Pathnex/sample-java-app.git'
            }
        }
        stage('Unit Test'){
            steps {
                sh 'mvn test -Dgroup=unit'
            }
        }
        stage('Integration Test'){
            steps {
                sh 'mvn verify -Dfroup=integration'
            }
        }
        stage('Report'){
            steps {
                sh 'echo "Test completed for $FIRM_NAME by $TEAM in $ENV environemt"'
            }
        }
    }
}
