pipeline {
    agent any 
    environment {
        INSTITUE_NAME = "Pathnex"
    }
    stages{
        stage('Checkout'){
            steps {
                 git url: 'https://github.com/Pathnex/sample-java-app.git'
            }
        }
        stage('Build'){
            steps {
                sh '''
                if [ -d ".m2" ]; then 
                   echo "Using cached dependencies
                else 
                  mvn clean compile
                fi
                '''
            }
        }
    }
}