// Jenkinsfile — Continuous Monitoring and Alerts in CI Pipeline

pipeline {
    agent any 
    stages {
        stage('Monitor'){
            steps {
                script {
                    echo 'Triggering CloudWatch alarms if CPU exceeds 80%'
                    sh 'aws cloudwatch put-metric-data --namespace "AWS/EC2" --metric-name "CPUUtilization" --value 90'
                }
            }
        }
        stage('Test'){
            steps {
                echo 'Running tests....'
            }
        }
    }
}