stages:
  - build 
  - push 
  - deploy 

build:
  stage: build 
  script:
    - docker build -t nephronix-web-app
push:
  stage: push
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker push nephronix-web-app

deploy:
  stage: deploy
  script:
    - helm repo add nephronix https://charts.nephronix.com
    - helm install nephronix-nginx nephronix/nginx-ingress