apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;
      location / {
      root /usr/share/nginx/html;
      index index.html index.htm;
      }
    }
---
  apiVersion: v1
  kind: Secret
  metadata:
    name: nginx-secret
  type: Opaque
  data:
    password: cGF0aG5leHBhc3M=
  
--- 
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: pathnex-nginx 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pathnex-nginx 
    template:
      metadata:
        labels: 
          app: pathnex-nginx 
      spec:
        containers:
          - name: nginx 
            image: nginx 
            volumeMounts:
              - mountPath: /etc/nginx/nginx.conf 
                name: nginx-config
                subPath: nginx.conf 
        volumes: 
          - name: nginx-config 
            configMap: 
              name: nginx-config 
          - name: nginx-secret 
            secret:
              secretName: nginx-secret 
              