pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    docker.build('pathnex-app')
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    kubectl apply -f kubernetes/deployment.yaml
                }
            }
        }
    }
}