//Jenkins Pipeline — Slack Notification

pipeline {
    agent any 
    environement {
        FIRM_NAME = "Nephronix"
        SLACK_CHANNEL = "#salesTeam"
    }

    stages {
        stage('Checkout'){
            steps {
                 git url: 'https://github.com/Pathnex/sample-java-app.git'
            }

        }
        stage('Build'){
            steps {
                sh 'mvn clean package'
            }
        }
    }

}

post {
    success {
        slackSend(channel: "$SLACK_CHANNEL", message: "SUCCESS: $FIRM_NAME Build #${env.BUILD_NUMBER}")
    }
    failure {
                slackSend(channel: "$SLACK_CHANNEL", message: "FAILURE: $FIRM_NAME Build #${env.BUILD_NUMBER}")

    }
}
