pipline {
    agent any
    stages {
        stage {
            stage('Checkoout') {
                steps {
                    git branch: 'main', url: 'https://github.com/Pathnex/sample-java-app.git'
                }
            }
            stage('Build') {
                steps {
                    sh '''
                     mvn clean compile || { echo "Compile failed"; exit 1; }
                    '''
                }
            }
            stage('Test') {
                steps {
                    sh '''
                   mvn test || { echo "Tests failed"; exit 1; }
                    '''
                }
            }
        }
    }
}
