# Kubernetes — Ingress with Nginx Controller

apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: nephronix-ingress
  annotation:
     nginx.ingress.kubernetes.io/rewrite-target: /
  spec:
    rules:
      - host: nephronix.local
        http:
          paths:
            - path: /
              pathType: Prefix 
              backend:
                service:
                  name: nephronix-service
                  port:
                    number: 80