pipeline {
    agent any 
    environment {
        IMAGE_NAME = 'nephronix-web-app'
    }
    stages {
        stage('Checkout'){
            steps {
                git 'https://github.com/pathnex/sample-repo.git'
            }
        }
        stage('Build Docker Image'){
            steps{
                script {
                    docker.build("${env.IMAGE_NAME}")
                }
            }
            stage('Push Docker Image'){
                steps {
                    docker.withRegistry('https://docker.io', 'docker-credentials'){
                    docker.image("${env.IMAGE_NAME}").push('latest') 
                }
            }
        }
    }
    stage('Deploy to Kubernetes'){
        steps{
            script {
                sh 'kubectl apply -f deployment.yaml'
            }
        }
    }
}