# Installing Helm on Remote Servers

- name: Install Helm 
  hosts: all 
  become: true 

  tasks: 
    - name: Download Helm 
      get_url:
        url: https://get.helm.sh/helm-v3.7.0-linux-amd64.tar.gz
        dest: /tmp/heml.tar.gz
      
    - name: Extract Helm 
      unarchive:
        src: /tmp/helm/tar.gz 
        dest: /usr/local/bin 
      remote_src: yes
    
    - name: Set Helm binary permissions
      file: 
        path: /usr/local/bin/helm 
        mode: '0755'

    # task - add a verify task
    - name: Verify Helm installation    
      command: helm version
      register: my_var
    
    - name: Print Helm version
      debug:
        msg: "{{ my_var.stdout }}"