## 🔹 Ansible Task — Install Nginx on Pathnex Server
---
 - name: Install Nginx on Pathnex server 
   hosts: all
   become: true

   tasks:
     - name: Install nginx 
       yum:
        name: nginx
        state: present

