# Ansible — Configure Firewall with iptables

- name: Configure Firewall with iptables 
  hosts: all 
  become: true 

  tasks:
    - name: Set default policies to drop all trafic 
      command: iptables -P INPUT DROP 
    - name: Allow SSH and HTTP traffic
      command: iptables -A INPUT -p tcp --dport 22 -j ACCEPT
      command: iptables -A INPUT -p tcp --dport 80 -j ACCEPT
    - name: Save iptables configuration
      command: service iptables save

