pipeline {
    agent any 
    environment {
        IMAGE_NAME = 'pathnex-web-app'
    }
    stages {
        stage('Build Docker Image'){
            steps {
                script {
                    docker.build("${env.IMAGE_NAME}")
                }
            }
        }
        stage('Push Docker Image'){
            steps {
                script {
                    docker.withRegistry('https:''docker.io', 'docker0credentials'){
                        docker.image("${env.IMAGE_NAME})".push('latest'))
                    }
                }
            }
        }

        stage('Deploy to Kubernetes'){
            steos {
                script {
                    sh 'kubectl apply -f deployment.yaml'
                }
            }
        }
    }
}