pipeline {
    agent any 
    environment {
        FIRM_NAME = "Nephronix"
    }
    stages {
        stage('Checkout'){
            steps {
                checkout scm 
            }
        }
        stage('Build'){
            steps{
                sh 'mvn clean compile'
            }
        }
    }
}