stages:
  - build 
  - test 
  - deploy

build:
  stage: build 
  script:
    - docker build -t nephronix-web-app

test:
  stage: test 
  script:
    - docker run nephronix-web-app npm test 
deploy:
  stage: deploy 
  script: 
    - kubectl apply -f kubernetes/deployment.yaml
