#🔹 Kubernetes — Horizontal Pod Autoscaler (HPA) with Load Balancer

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nephronix-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nephronix-web-app 
    template:
      metadata:
        labels: 
          app: nephronix-web-app 
      spec: 
        containers:
          - name: web 
            image: nginx 
            ports:
              - containerPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nephronix-web-app-hpa 
spec:
  scaleTargetRef:
    apiVersion: app/v1 
    kind: Deployment 
    name: nephronix-web-app 
  minReplicas: 1
  maxReplicas: 5
  targetCPUtilizationPercentage: 80
  

