## 🔹 Ansible — Use Jinja2 Template

---
  - name: Deploy template for Pathnex
    hosts: all 
    become: true 

    tasks:
      - name: Copy template file
        template:
          src: pathnex.conf.j2
          dest: /etc/pathnex.conf