# Kubernetes — Federated Deployment with Multiple Clusters

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nephronix-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nephronix-app
  template:
    metadata:
      labels: 
        app: nephronix-app 
    spec: 
      containers:
        - name: nginx
          image: nginx 
          ports:
            - containerPort: 80
---
  apiVersion: federation.k8s.io/v1beta1
  kind: FederatedDeployment
  metadata:
    name: nephronix-federated-deployment
    namespace: default
  spec:
    template:
      spec:
        replicas: 3
        selector:
          matchLabels: 
            app: nephronix-app 
        template:
          metadata: 
            labels: 
              app: nephronix-app 
          spec:
            containers: 
              - name: nginx 
                image: nginx 
                ports: 
                  - containerPort: 80