# Compose with MySQL

version: '3'
services:
    db:
        image: mysql:8
        container_name: nephronix-db
        envrironment:
            MYSQL_ROOT_PASSWORD: root 
        web:
            image: nginx
            container_name: nephronix-web
