## Day 7 - Speed Typing


## 1. Jenkins Pipeline — Parameterized

pipeline {
 agent any
 parameters {

     string(name: 'ENVIRONMENT', defaultValue: 'dev', description: 'Deployment Environment')
 }
 environment {
    INSTITUTE_NAME = "Pathnex"
    }
 stages {
    stage('Checkout'){
       steps {
           git url: 'https://github.com/Pathnex/sample-java-app.git'

       }
    }
    stage ('Deploy') {
       steps {
         sh 'echo "Deploying to $ENVIRONMENT by $INSTITUTE_NAME"'
         }
    }
}
}

## 2. GitLab CI — Parameterized via Variables

stages:
  - deploy

variables:
   INSTITUTE_NAME: "Pathnex"
   ENVIRONMENT: "dev"


deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying to $ENVIRONMENT by $INSTITUTE_NAME"

