# Day 09 — Templates, Internet Gateway, ConfigMap, CPU Load


## 1. 🔹 Ansible — Use Jinja2 Template

---

 - name: Deploy template for Pathnex
   hosts: all
   become: yes


   tasks:
     - name: Copy template file
       template: 
         src: pathnex.conf.j2
         dest: /etc/pathnex.conf




## 2. 🔹 Terraform — Internet Gateway

resource "aws_internet_gateway" "PathnexIGW" {
     vpc_id = aws_vpc.PathnexVPC.id
    
    tags = {
      Name: "Pathnex-IGW"
    }
}

## 3. 🔹 Kubernetes — Create ConfigMap

apiVersion: v1
kind: ConfigMap
metadata:
    name: pathnex-ConfigMap
data:
  APP_MODE: "production"
  WELCOME_MSG: "Hello Pathnex"


## 4. 🔹 Shell Script — Check CPU Load

#!/bin/bash

LOAD=$(uptime | awk '{print $10}')

echo "Current CPU Load: $LOAD"




## 5. 🔹 Jenkins Pipeline — Archive Artifacts
pipeline {
agent any 
environment {
INSTITUTE_NAME = "Pathnex"
}

stages {
      stage('Checkout'){
      steps {
       git url: 'https://github.com/Pathnex/sample-java-app.git'
      }
      }
      stage('Build') {
        steps {
          sh 'mvn clean package'
        }
      }
      stage('Archive'){
        steps {
          archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
        }
      }
}








}




## 6. 🔹 GitLab CI — Artifacts

stages:
   - build

 build:
   stage: build
   image: maven:3.8.1-jdk-17
   script:
    - git clone https://github.com/Pathnex/sample-java-app.git
    - cd sample-java-app
    - mvn clean package
  artifacts:
    paths:
    - target/*.jar
    expire_in: 1 week
