// Jenkinsfile — Multi-Environment Deployment

pipeline {
    agent any 
    environment {
        IMAGE_NAME = 'nephronix-web-app'
        DEPLOY_ENV = 'production'
    }

    stages {
        stage('Build'){
            steps {
                echo 'Building Docker image'
                docker.build("${env.IMAGE_NAME}")
            }
        }
    stage('Test'){
        steps {
            echo 'Running tests...'
        }
    }
    stage('Deploy to Kubernetes') {
        steps {
            script {
                if(env.DEPLOY_ENV == 'production'){
                    sh 'kubectl apply -f kubernetes/prod-deployment.yaml'
        
                }else{
                    sh 'kubectl apply 0f kubernetes/dev-deployment.yaml'
                }
            }
        }
    }
    }
}
